### ISSUE TITLE
Why not use triggers?

### ISSUE THREAD

**Issue by bf4** [derkan/pg_party#1]

**Comment by derkan** [comment]
On trigger usage, you can not get inserted id if record is insert to master table or use RETURNING clause.(Trigger to check and create new partition should return NULL). And as NULL is returned, you'll see "0 records inserted" after a successful insert.(If not RETURN NULL is returned, you'll end up with [duplicate record](http://dba.stackexchange.com/questions/102664/postgres-partition-table-trigger-inserting-duplicate-records)

If you should use triggers, to overcome discussed issue above you may use [INSTEAD OF clause with a procedure](http://stackoverflow.com/questions/22026354/insert-trigger-ends-up-inserting-duplicate-rows-in-partitioned-table).

An another advantage of pg_party is, pre-creating of partitions and indexes-constraints is performative on heavy insert systems.

**Comment by derkan** [comment]
Since there have been no more responses for a while, I am closing this.
